server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/rsbank
    username: postgres
    password: root
  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      
logging:
  level:
    org:
      hibernate:
        sql: DEBUG

build:
  version: "2.0"

accounts:
  message: "Welcome to RSBank accounts related local dev APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "{cipher}39415ea0caaf781dd65c77ffe4e5370ded25ad49cc7e5b43885e42a9738d3ab8"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345
