server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/rsbank
    username: postgres
    password: root
  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Application"
    version: "1.0.0"

build:
  version: "2.0"

cards:
  message: "Welcome to RSBank cards related local dev APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@rsbank.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345
